drone: true
case: true
camera: false
lora: true
system_address: serial:///dev/ttyACM0:115200
target1:
  latitude: 40.14253806
  longitude: 139.98724388
  altitude: 5
time_fin: 300
target2:
  latitude: 35.7138415
  longitude: 139.76050941
mode: mission
hsv:
  h:
  - 0
  - 15
  s:
  - 85
  - 255
  v:
  - 0
  - 255
nichrome_time: 5
setting_presen_time: 0.03
writing_presen_time: 0.03
presen_rest_time: 0.03
ligsen_rest_time: 0.03
judge_storage_maxtime: 300
judge_storage_loop_time: 0.5
judge_storage_border_light: 500
judge_release_maxtime: 180
judge_release_border_light: 500
judge_landing_maxtime: 30
judge_landing_sleep_time: 2
pre_count_max: 30
pressure_tolerance: 0.08
maxmax_time: 600
disp_pressure_interval: 0.2
judge_storage_countmax: 60
judge_release_pre_countmax: 4
judge_release_mintime: 0
disp_pressure_interval_saigonotoride: 3
saigonotoride_disp_pressure: 2
